services:
  - redis-server

before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - sudo psql --version
  - phantomjs --version
  - sudo apt-get install postgresql-contrib-9.3 -qq
  - sudo /etc/init.d/postgresql restart
  - psql -c 'create database gaku_test;' -U postgres

bundler_args: --without production

before_install:
  - export BUNDLE_GEMFILE="`pwd`/Gemfile"

script:
  - bundle exec rake test_app
  - I18N=1 bundle exec rspec

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#gaku"

rvm:
  - 2.2